# Generated by Django 2.2.3 on 2019-07-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restname', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('cuisine', models.CharField(max_length=200)),
                ('last_modify_date', models.DateTimeField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueRating', models.IntegerField()),
                ('atmosRating', models.IntegerField()),
                ('serviceRating', models.IntegerField()),
                ('foodRating', models.IntegerField()),
                ('overallRating', models.DecimalField(decimal_places=5, max_digits=10)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('comment', models.TextField()),
                ('dateofvisit', models.DateField()),
                ('created', models.DateTimeField()),
                ('restid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodreview.Restaurant')),
            ],
        ),
    ]
