# Generated by Django 2.2.3 on 2019-07-13 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodreview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='regionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodreview.Region'),
        ),
        migrations.AddField(
            model_name='like',
            name='reviewid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodreview.Review'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
