# Generated by Django 2.2.3 on 2019-07-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodreview', '0002_auto_20190713_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='overallRating',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
