# Generated by Django 2.2.3 on 2019-07-14 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodreview', '0003_auto_20190714_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='atmosRating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='foodRating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='serviceRating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='valueRating',
        ),
        migrations.AlterField(
            model_name='review',
            name='overallRating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
