# Generated by Django 2.2.3 on 2019-07-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodreview', '0004_auto_20190714_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='restid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodreview.Restaurant', verbose_name='Restaurant'),
        ),
    ]
