# Generated by Django 2.2.3 on 2019-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodreview', '0005_auto_20190714_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='dateofvisit',
            field=models.DateField(verbose_name='Date of Visit (YYYY/MM/DD)'),
        ),
    ]
