# Generated by Django 2.2.3 on 2019-07-15 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodreview', '0007_review_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('restid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodreview.Restaurant', verbose_name='Restaurant')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodreview.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
