# Generated by Django 2.2.3 on 2019-07-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodreview', '0008_reviewinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': (('all_review', 'Read all reviews'),)},
        ),
    ]
